// Code generated by "enumer -type=ArtifactActionIndex -json"; DO NOT EDIT.

package game

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ArtifactActionIndexName = "FirstArtifactActionSecondArtifactAction"

var _ArtifactActionIndexIndex = [...]uint8{0, 19, 39}

const _ArtifactActionIndexLowerName = "firstartifactactionsecondartifactaction"

func (i ArtifactActionIndex) String() string {
	if i < 0 || i >= ArtifactActionIndex(len(_ArtifactActionIndexIndex)-1) {
		return fmt.Sprintf("ArtifactActionIndex(%d)", i)
	}
	return _ArtifactActionIndexName[_ArtifactActionIndexIndex[i]:_ArtifactActionIndexIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ArtifactActionIndexNoOp() {
	var x [1]struct{}
	_ = x[FirstArtifactAction-(0)]
	_ = x[SecondArtifactAction-(1)]
}

var _ArtifactActionIndexValues = []ArtifactActionIndex{FirstArtifactAction, SecondArtifactAction}

var _ArtifactActionIndexNameToValueMap = map[string]ArtifactActionIndex{
	_ArtifactActionIndexName[0:19]:       FirstArtifactAction,
	_ArtifactActionIndexLowerName[0:19]:  FirstArtifactAction,
	_ArtifactActionIndexName[19:39]:      SecondArtifactAction,
	_ArtifactActionIndexLowerName[19:39]: SecondArtifactAction,
}

var _ArtifactActionIndexNames = []string{
	_ArtifactActionIndexName[0:19],
	_ArtifactActionIndexName[19:39],
}

// ArtifactActionIndexString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ArtifactActionIndexString(s string) (ArtifactActionIndex, error) {
	if val, ok := _ArtifactActionIndexNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ArtifactActionIndexNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ArtifactActionIndex values", s)
}

// ArtifactActionIndexValues returns all values of the enum
func ArtifactActionIndexValues() []ArtifactActionIndex {
	return _ArtifactActionIndexValues
}

// ArtifactActionIndexStrings returns a slice of all String values of the enum
func ArtifactActionIndexStrings() []string {
	strs := make([]string, len(_ArtifactActionIndexNames))
	copy(strs, _ArtifactActionIndexNames)
	return strs
}

// IsAArtifactActionIndex returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ArtifactActionIndex) IsAArtifactActionIndex() bool {
	for _, v := range _ArtifactActionIndexValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ArtifactActionIndex
func (i ArtifactActionIndex) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ArtifactActionIndex
func (i *ArtifactActionIndex) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ArtifactActionIndex should be a string, got %s", data)
	}

	var err error
	*i, err = ArtifactActionIndexString(s)
	return err
}
