// Code generated by "enumer -type=DeckColor -json"; DO NOT EDIT.

package game

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DeckColorName = "NoColorBlueGreenPurpleYellowRedBlack"

var _DeckColorIndex = [...]uint8{0, 7, 11, 16, 22, 28, 31, 36}

const _DeckColorLowerName = "nocolorbluegreenpurpleyellowredblack"

func (i DeckColor) String() string {
	if i < 0 || i >= DeckColor(len(_DeckColorIndex)-1) {
		return fmt.Sprintf("DeckColor(%d)", i)
	}
	return _DeckColorName[_DeckColorIndex[i]:_DeckColorIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DeckColorNoOp() {
	var x [1]struct{}
	_ = x[NoColor-(0)]
	_ = x[Blue-(1)]
	_ = x[Green-(2)]
	_ = x[Purple-(3)]
	_ = x[Yellow-(4)]
	_ = x[Red-(5)]
	_ = x[Black-(6)]
}

var _DeckColorValues = []DeckColor{NoColor, Blue, Green, Purple, Yellow, Red, Black}

var _DeckColorNameToValueMap = map[string]DeckColor{
	_DeckColorName[0:7]:        NoColor,
	_DeckColorLowerName[0:7]:   NoColor,
	_DeckColorName[7:11]:       Blue,
	_DeckColorLowerName[7:11]:  Blue,
	_DeckColorName[11:16]:      Green,
	_DeckColorLowerName[11:16]: Green,
	_DeckColorName[16:22]:      Purple,
	_DeckColorLowerName[16:22]: Purple,
	_DeckColorName[22:28]:      Yellow,
	_DeckColorLowerName[22:28]: Yellow,
	_DeckColorName[28:31]:      Red,
	_DeckColorLowerName[28:31]: Red,
	_DeckColorName[31:36]:      Black,
	_DeckColorLowerName[31:36]: Black,
}

var _DeckColorNames = []string{
	_DeckColorName[0:7],
	_DeckColorName[7:11],
	_DeckColorName[11:16],
	_DeckColorName[16:22],
	_DeckColorName[22:28],
	_DeckColorName[28:31],
	_DeckColorName[31:36],
}

// DeckColorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DeckColorString(s string) (DeckColor, error) {
	if val, ok := _DeckColorNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DeckColorNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DeckColor values", s)
}

// DeckColorValues returns all values of the enum
func DeckColorValues() []DeckColor {
	return _DeckColorValues
}

// DeckColorStrings returns a slice of all String values of the enum
func DeckColorStrings() []string {
	strs := make([]string, len(_DeckColorNames))
	copy(strs, _DeckColorNames)
	return strs
}

// IsADeckColor returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DeckColor) IsADeckColor() bool {
	for _, v := range _DeckColorValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DeckColor
func (i DeckColor) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DeckColor
func (i *DeckColor) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DeckColor should be a string, got %s", data)
	}

	var err error
	*i, err = DeckColorString(s)
	return err
}
