// Code generated by "enumer -type=DungeonCardKind -json"; DO NOT EDIT.

package game

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _DungeonCardKindName = "CardMonsterCardObstacleCardPersonCardMiniBossCardEventCardCurseCardBoss"

var _DungeonCardKindIndex = [...]uint8{0, 11, 23, 33, 45, 54, 63, 71}

const _DungeonCardKindLowerName = "cardmonstercardobstaclecardpersoncardminibosscardeventcardcursecardboss"

func (i DungeonCardKind) String() string {
	if i < 0 || i >= DungeonCardKind(len(_DungeonCardKindIndex)-1) {
		return fmt.Sprintf("DungeonCardKind(%d)", i)
	}
	return _DungeonCardKindName[_DungeonCardKindIndex[i]:_DungeonCardKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DungeonCardKindNoOp() {
	var x [1]struct{}
	_ = x[CardMonster-(0)]
	_ = x[CardObstacle-(1)]
	_ = x[CardPerson-(2)]
	_ = x[CardMiniBoss-(3)]
	_ = x[CardEvent-(4)]
	_ = x[CardCurse-(5)]
	_ = x[CardBoss-(6)]
}

var _DungeonCardKindValues = []DungeonCardKind{CardMonster, CardObstacle, CardPerson, CardMiniBoss, CardEvent, CardCurse, CardBoss}

var _DungeonCardKindNameToValueMap = map[string]DungeonCardKind{
	_DungeonCardKindName[0:11]:       CardMonster,
	_DungeonCardKindLowerName[0:11]:  CardMonster,
	_DungeonCardKindName[11:23]:      CardObstacle,
	_DungeonCardKindLowerName[11:23]: CardObstacle,
	_DungeonCardKindName[23:33]:      CardPerson,
	_DungeonCardKindLowerName[23:33]: CardPerson,
	_DungeonCardKindName[33:45]:      CardMiniBoss,
	_DungeonCardKindLowerName[33:45]: CardMiniBoss,
	_DungeonCardKindName[45:54]:      CardEvent,
	_DungeonCardKindLowerName[45:54]: CardEvent,
	_DungeonCardKindName[54:63]:      CardCurse,
	_DungeonCardKindLowerName[54:63]: CardCurse,
	_DungeonCardKindName[63:71]:      CardBoss,
	_DungeonCardKindLowerName[63:71]: CardBoss,
}

var _DungeonCardKindNames = []string{
	_DungeonCardKindName[0:11],
	_DungeonCardKindName[11:23],
	_DungeonCardKindName[23:33],
	_DungeonCardKindName[33:45],
	_DungeonCardKindName[45:54],
	_DungeonCardKindName[54:63],
	_DungeonCardKindName[63:71],
}

// DungeonCardKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DungeonCardKindString(s string) (DungeonCardKind, error) {
	if val, ok := _DungeonCardKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DungeonCardKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DungeonCardKind values", s)
}

// DungeonCardKindValues returns all values of the enum
func DungeonCardKindValues() []DungeonCardKind {
	return _DungeonCardKindValues
}

// DungeonCardKindStrings returns a slice of all String values of the enum
func DungeonCardKindStrings() []string {
	strs := make([]string, len(_DungeonCardKindNames))
	copy(strs, _DungeonCardKindNames)
	return strs
}

// IsADungeonCardKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DungeonCardKind) IsADungeonCardKind() bool {
	for _, v := range _DungeonCardKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for DungeonCardKind
func (i DungeonCardKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for DungeonCardKind
func (i *DungeonCardKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("DungeonCardKind should be a string, got %s", data)
	}

	var err error
	*i, err = DungeonCardKindString(s)
	return err
}
