// Code generated by "enumer -type=GameCurseEffect -json"; DO NOT EDIT.

package game

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _GameCurseEffectName = "NoEffectTimeCannotBeStoppedActionsCannotBePlayedAbilitiesCannotBePlayedDoorsOpenInPairsHandSizeLimitedToThreeFlippedHeroMatThreeDiscardsWhenTimeStopsHandsHiddenPlayersHandFacingAwayPlayersCanOnlyUseOneHandToPlayPlayersMustOnlySayWafflesPlayersMustOnlySayMeow"

var _GameCurseEffectIndex = [...]uint16{0, 8, 27, 48, 71, 87, 109, 123, 149, 160, 181, 211, 236, 258}

const _GameCurseEffectLowerName = "noeffecttimecannotbestoppedactionscannotbeplayedabilitiescannotbeplayeddoorsopeninpairshandsizelimitedtothreeflippedheromatthreediscardswhentimestopshandshiddenplayershandfacingawayplayerscanonlyuseonehandtoplayplayersmustonlysaywafflesplayersmustonlysaymeow"

func (i GameCurseEffect) String() string {
	if i < 0 || i >= GameCurseEffect(len(_GameCurseEffectIndex)-1) {
		return fmt.Sprintf("GameCurseEffect(%d)", i)
	}
	return _GameCurseEffectName[_GameCurseEffectIndex[i]:_GameCurseEffectIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GameCurseEffectNoOp() {
	var x [1]struct{}
	_ = x[NoEffect-(0)]
	_ = x[TimeCannotBeStopped-(1)]
	_ = x[ActionsCannotBePlayed-(2)]
	_ = x[AbilitiesCannotBePlayed-(3)]
	_ = x[DoorsOpenInPairs-(4)]
	_ = x[HandSizeLimitedToThree-(5)]
	_ = x[FlippedHeroMat-(6)]
	_ = x[ThreeDiscardsWhenTimeStops-(7)]
	_ = x[HandsHidden-(8)]
	_ = x[PlayersHandFacingAway-(9)]
	_ = x[PlayersCanOnlyUseOneHandToPlay-(10)]
	_ = x[PlayersMustOnlySayWaffles-(11)]
	_ = x[PlayersMustOnlySayMeow-(12)]
}

var _GameCurseEffectValues = []GameCurseEffect{NoEffect, TimeCannotBeStopped, ActionsCannotBePlayed, AbilitiesCannotBePlayed, DoorsOpenInPairs, HandSizeLimitedToThree, FlippedHeroMat, ThreeDiscardsWhenTimeStops, HandsHidden, PlayersHandFacingAway, PlayersCanOnlyUseOneHandToPlay, PlayersMustOnlySayWaffles, PlayersMustOnlySayMeow}

var _GameCurseEffectNameToValueMap = map[string]GameCurseEffect{
	_GameCurseEffectName[0:8]:          NoEffect,
	_GameCurseEffectLowerName[0:8]:     NoEffect,
	_GameCurseEffectName[8:27]:         TimeCannotBeStopped,
	_GameCurseEffectLowerName[8:27]:    TimeCannotBeStopped,
	_GameCurseEffectName[27:48]:        ActionsCannotBePlayed,
	_GameCurseEffectLowerName[27:48]:   ActionsCannotBePlayed,
	_GameCurseEffectName[48:71]:        AbilitiesCannotBePlayed,
	_GameCurseEffectLowerName[48:71]:   AbilitiesCannotBePlayed,
	_GameCurseEffectName[71:87]:        DoorsOpenInPairs,
	_GameCurseEffectLowerName[71:87]:   DoorsOpenInPairs,
	_GameCurseEffectName[87:109]:       HandSizeLimitedToThree,
	_GameCurseEffectLowerName[87:109]:  HandSizeLimitedToThree,
	_GameCurseEffectName[109:123]:      FlippedHeroMat,
	_GameCurseEffectLowerName[109:123]: FlippedHeroMat,
	_GameCurseEffectName[123:149]:      ThreeDiscardsWhenTimeStops,
	_GameCurseEffectLowerName[123:149]: ThreeDiscardsWhenTimeStops,
	_GameCurseEffectName[149:160]:      HandsHidden,
	_GameCurseEffectLowerName[149:160]: HandsHidden,
	_GameCurseEffectName[160:181]:      PlayersHandFacingAway,
	_GameCurseEffectLowerName[160:181]: PlayersHandFacingAway,
	_GameCurseEffectName[181:211]:      PlayersCanOnlyUseOneHandToPlay,
	_GameCurseEffectLowerName[181:211]: PlayersCanOnlyUseOneHandToPlay,
	_GameCurseEffectName[211:236]:      PlayersMustOnlySayWaffles,
	_GameCurseEffectLowerName[211:236]: PlayersMustOnlySayWaffles,
	_GameCurseEffectName[236:258]:      PlayersMustOnlySayMeow,
	_GameCurseEffectLowerName[236:258]: PlayersMustOnlySayMeow,
}

var _GameCurseEffectNames = []string{
	_GameCurseEffectName[0:8],
	_GameCurseEffectName[8:27],
	_GameCurseEffectName[27:48],
	_GameCurseEffectName[48:71],
	_GameCurseEffectName[71:87],
	_GameCurseEffectName[87:109],
	_GameCurseEffectName[109:123],
	_GameCurseEffectName[123:149],
	_GameCurseEffectName[149:160],
	_GameCurseEffectName[160:181],
	_GameCurseEffectName[181:211],
	_GameCurseEffectName[211:236],
	_GameCurseEffectName[236:258],
}

// GameCurseEffectString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GameCurseEffectString(s string) (GameCurseEffect, error) {
	if val, ok := _GameCurseEffectNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GameCurseEffectNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GameCurseEffect values", s)
}

// GameCurseEffectValues returns all values of the enum
func GameCurseEffectValues() []GameCurseEffect {
	return _GameCurseEffectValues
}

// GameCurseEffectStrings returns a slice of all String values of the enum
func GameCurseEffectStrings() []string {
	strs := make([]string, len(_GameCurseEffectNames))
	copy(strs, _GameCurseEffectNames)
	return strs
}

// IsAGameCurseEffect returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GameCurseEffect) IsAGameCurseEffect() bool {
	for _, v := range _GameCurseEffectValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for GameCurseEffect
func (i GameCurseEffect) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for GameCurseEffect
func (i *GameCurseEffect) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("GameCurseEffect should be a string, got %s", data)
	}

	var err error
	*i, err = GameCurseEffectString(s)
	return err
}
