// Code generated by "enumer -type=HeroClass -json"; DO NOT EDIT.

package game

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _HeroClassName = "SorceressWizardHuntressRangerNinjaThiefPaladinValkyrieBarbarianGladiatorDruidShaman"

var _HeroClassIndex = [...]uint8{0, 9, 15, 23, 29, 34, 39, 46, 54, 63, 72, 77, 83}

const _HeroClassLowerName = "sorceresswizardhuntressrangerninjathiefpaladinvalkyriebarbariangladiatordruidshaman"

func (i HeroClass) String() string {
	if i < 0 || i >= HeroClass(len(_HeroClassIndex)-1) {
		return fmt.Sprintf("HeroClass(%d)", i)
	}
	return _HeroClassName[_HeroClassIndex[i]:_HeroClassIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _HeroClassNoOp() {
	var x [1]struct{}
	_ = x[Sorceress-(0)]
	_ = x[Wizard-(1)]
	_ = x[Huntress-(2)]
	_ = x[Ranger-(3)]
	_ = x[Ninja-(4)]
	_ = x[Thief-(5)]
	_ = x[Paladin-(6)]
	_ = x[Valkyrie-(7)]
	_ = x[Barbarian-(8)]
	_ = x[Gladiator-(9)]
	_ = x[Druid-(10)]
	_ = x[Shaman-(11)]
}

var _HeroClassValues = []HeroClass{Sorceress, Wizard, Huntress, Ranger, Ninja, Thief, Paladin, Valkyrie, Barbarian, Gladiator, Druid, Shaman}

var _HeroClassNameToValueMap = map[string]HeroClass{
	_HeroClassName[0:9]:        Sorceress,
	_HeroClassLowerName[0:9]:   Sorceress,
	_HeroClassName[9:15]:       Wizard,
	_HeroClassLowerName[9:15]:  Wizard,
	_HeroClassName[15:23]:      Huntress,
	_HeroClassLowerName[15:23]: Huntress,
	_HeroClassName[23:29]:      Ranger,
	_HeroClassLowerName[23:29]: Ranger,
	_HeroClassName[29:34]:      Ninja,
	_HeroClassLowerName[29:34]: Ninja,
	_HeroClassName[34:39]:      Thief,
	_HeroClassLowerName[34:39]: Thief,
	_HeroClassName[39:46]:      Paladin,
	_HeroClassLowerName[39:46]: Paladin,
	_HeroClassName[46:54]:      Valkyrie,
	_HeroClassLowerName[46:54]: Valkyrie,
	_HeroClassName[54:63]:      Barbarian,
	_HeroClassLowerName[54:63]: Barbarian,
	_HeroClassName[63:72]:      Gladiator,
	_HeroClassLowerName[63:72]: Gladiator,
	_HeroClassName[72:77]:      Druid,
	_HeroClassLowerName[72:77]: Druid,
	_HeroClassName[77:83]:      Shaman,
	_HeroClassLowerName[77:83]: Shaman,
}

var _HeroClassNames = []string{
	_HeroClassName[0:9],
	_HeroClassName[9:15],
	_HeroClassName[15:23],
	_HeroClassName[23:29],
	_HeroClassName[29:34],
	_HeroClassName[34:39],
	_HeroClassName[39:46],
	_HeroClassName[46:54],
	_HeroClassName[54:63],
	_HeroClassName[63:72],
	_HeroClassName[72:77],
	_HeroClassName[77:83],
}

// HeroClassString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func HeroClassString(s string) (HeroClass, error) {
	if val, ok := _HeroClassNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _HeroClassNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to HeroClass values", s)
}

// HeroClassValues returns all values of the enum
func HeroClassValues() []HeroClass {
	return _HeroClassValues
}

// HeroClassStrings returns a slice of all String values of the enum
func HeroClassStrings() []string {
	strs := make([]string, len(_HeroClassNames))
	copy(strs, _HeroClassNames)
	return strs
}

// IsAHeroClass returns "true" if the value is listed in the enum definition. "false" otherwise
func (i HeroClass) IsAHeroClass() bool {
	for _, v := range _HeroClassValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for HeroClass
func (i HeroClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for HeroClass
func (i *HeroClass) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("HeroClass should be a string, got %s", data)
	}

	var err error
	*i, err = HeroClassString(s)
	return err
}
