// Code generated by "enumer -type=PlayerCardKind -json"; DO NOT EDIT.

package game

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PlayerCardKindName = "PlayerCardResourcePlayerCardAction"

var _PlayerCardKindIndex = [...]uint8{0, 18, 34}

const _PlayerCardKindLowerName = "playercardresourceplayercardaction"

func (i PlayerCardKind) String() string {
	if i < 0 || i >= PlayerCardKind(len(_PlayerCardKindIndex)-1) {
		return fmt.Sprintf("PlayerCardKind(%d)", i)
	}
	return _PlayerCardKindName[_PlayerCardKindIndex[i]:_PlayerCardKindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PlayerCardKindNoOp() {
	var x [1]struct{}
	_ = x[PlayerCardResource-(0)]
	_ = x[PlayerCardAction-(1)]
}

var _PlayerCardKindValues = []PlayerCardKind{PlayerCardResource, PlayerCardAction}

var _PlayerCardKindNameToValueMap = map[string]PlayerCardKind{
	_PlayerCardKindName[0:18]:       PlayerCardResource,
	_PlayerCardKindLowerName[0:18]:  PlayerCardResource,
	_PlayerCardKindName[18:34]:      PlayerCardAction,
	_PlayerCardKindLowerName[18:34]: PlayerCardAction,
}

var _PlayerCardKindNames = []string{
	_PlayerCardKindName[0:18],
	_PlayerCardKindName[18:34],
}

// PlayerCardKindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PlayerCardKindString(s string) (PlayerCardKind, error) {
	if val, ok := _PlayerCardKindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PlayerCardKindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PlayerCardKind values", s)
}

// PlayerCardKindValues returns all values of the enum
func PlayerCardKindValues() []PlayerCardKind {
	return _PlayerCardKindValues
}

// PlayerCardKindStrings returns a slice of all String values of the enum
func PlayerCardKindStrings() []string {
	strs := make([]string, len(_PlayerCardKindNames))
	copy(strs, _PlayerCardKindNames)
	return strs
}

// IsAPlayerCardKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PlayerCardKind) IsAPlayerCardKind() bool {
	for _, v := range _PlayerCardKindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PlayerCardKind
func (i PlayerCardKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PlayerCardKind
func (i *PlayerCardKind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PlayerCardKind should be a string, got %s", data)
	}

	var err error
	*i, err = PlayerCardKindString(s)
	return err
}
