// Code generated by "enumer -type=ResourceType -json"; DO NOT EDIT.

package game

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ResourceTypeName = "NoResourceSwordArrowShieldJumpScrollWildCardInfiniteSwordInfiniteArrowInfiniteShieldInfiniteJumpInfiniteScroll"

var _ResourceTypeIndex = [...]uint8{0, 10, 15, 20, 26, 30, 36, 44, 57, 70, 84, 96, 110}

const _ResourceTypeLowerName = "noresourceswordarrowshieldjumpscrollwildcardinfiniteswordinfinitearrowinfiniteshieldinfinitejumpinfinitescroll"

func (i ResourceType) String() string {
	if i < 0 || i >= ResourceType(len(_ResourceTypeIndex)-1) {
		return fmt.Sprintf("ResourceType(%d)", i)
	}
	return _ResourceTypeName[_ResourceTypeIndex[i]:_ResourceTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ResourceTypeNoOp() {
	var x [1]struct{}
	_ = x[NoResource-(0)]
	_ = x[Sword-(1)]
	_ = x[Arrow-(2)]
	_ = x[Shield-(3)]
	_ = x[Jump-(4)]
	_ = x[Scroll-(5)]
	_ = x[WildCard-(6)]
	_ = x[InfiniteSword-(7)]
	_ = x[InfiniteArrow-(8)]
	_ = x[InfiniteShield-(9)]
	_ = x[InfiniteJump-(10)]
	_ = x[InfiniteScroll-(11)]
}

var _ResourceTypeValues = []ResourceType{NoResource, Sword, Arrow, Shield, Jump, Scroll, WildCard, InfiniteSword, InfiniteArrow, InfiniteShield, InfiniteJump, InfiniteScroll}

var _ResourceTypeNameToValueMap = map[string]ResourceType{
	_ResourceTypeName[0:10]:        NoResource,
	_ResourceTypeLowerName[0:10]:   NoResource,
	_ResourceTypeName[10:15]:       Sword,
	_ResourceTypeLowerName[10:15]:  Sword,
	_ResourceTypeName[15:20]:       Arrow,
	_ResourceTypeLowerName[15:20]:  Arrow,
	_ResourceTypeName[20:26]:       Shield,
	_ResourceTypeLowerName[20:26]:  Shield,
	_ResourceTypeName[26:30]:       Jump,
	_ResourceTypeLowerName[26:30]:  Jump,
	_ResourceTypeName[30:36]:       Scroll,
	_ResourceTypeLowerName[30:36]:  Scroll,
	_ResourceTypeName[36:44]:       WildCard,
	_ResourceTypeLowerName[36:44]:  WildCard,
	_ResourceTypeName[44:57]:       InfiniteSword,
	_ResourceTypeLowerName[44:57]:  InfiniteSword,
	_ResourceTypeName[57:70]:       InfiniteArrow,
	_ResourceTypeLowerName[57:70]:  InfiniteArrow,
	_ResourceTypeName[70:84]:       InfiniteShield,
	_ResourceTypeLowerName[70:84]:  InfiniteShield,
	_ResourceTypeName[84:96]:       InfiniteJump,
	_ResourceTypeLowerName[84:96]:  InfiniteJump,
	_ResourceTypeName[96:110]:      InfiniteScroll,
	_ResourceTypeLowerName[96:110]: InfiniteScroll,
}

var _ResourceTypeNames = []string{
	_ResourceTypeName[0:10],
	_ResourceTypeName[10:15],
	_ResourceTypeName[15:20],
	_ResourceTypeName[20:26],
	_ResourceTypeName[26:30],
	_ResourceTypeName[30:36],
	_ResourceTypeName[36:44],
	_ResourceTypeName[44:57],
	_ResourceTypeName[57:70],
	_ResourceTypeName[70:84],
	_ResourceTypeName[84:96],
	_ResourceTypeName[96:110],
}

// ResourceTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ResourceTypeString(s string) (ResourceType, error) {
	if val, ok := _ResourceTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ResourceTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ResourceType values", s)
}

// ResourceTypeValues returns all values of the enum
func ResourceTypeValues() []ResourceType {
	return _ResourceTypeValues
}

// ResourceTypeStrings returns a slice of all String values of the enum
func ResourceTypeStrings() []string {
	strs := make([]string, len(_ResourceTypeNames))
	copy(strs, _ResourceTypeNames)
	return strs
}

// IsAResourceType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ResourceType) IsAResourceType() bool {
	for _, v := range _ResourceTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ResourceType
func (i ResourceType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ResourceType
func (i *ResourceType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ResourceType should be a string, got %s", data)
	}

	var err error
	*i, err = ResourceTypeString(s)
	return err
}
